url: https://newer.thewrongsongs.com
baseurl: /

# Site settings
title: The Wrong Songs
email: erwin@thewrongsongs.com
phone: +31 (0)6 38 53 73 25
description: "The Wrong Songs is een bureau voor online strategie in Utrecht."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2B99BF
  secondary: 1C667F
  secondary-dark: 262626
  darkestbackground: 262626

# Team names, titles and social links
people:
- name: Erwin Elling
  pic: 1
  position: Flaphaas
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: ??
  pic: 2
  position: flappie
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Vechtclub XL
  - line: Europalaan 2B, E1.2
  - line: Utrecht

# Build settings
markdown: kramdown
permalink: pretty